// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Neko2h/shortener/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// LinkUsecase is an autogenerated mock type for the LinkUsecase type
type LinkUsecase struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *LinkUsecase) Get(_a0 context.Context, _a1 string) (*entity.Link, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *entity.Link
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.Link); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// New provides a mock function with given fields: _a0, _a1
func (_m *LinkUsecase) New(_a0 context.Context, _a1 *entity.Link) (*entity.Link, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *entity.Link
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Link) *entity.Link); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Link)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *entity.Link) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type NewLinkUsecaseT interface {
	mock.TestingT
	Cleanup(func())
}

// NewLinkUsecase creates a new instance of LinkUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLinkUsecase(t NewLinkUsecaseT) *LinkUsecase {
	mock := &LinkUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
