version: "3.9"
services:
  app:
     container_name: app
     build:
       context: .
       dockerfile: build.dockerfile
     ports:
       - 8080:8080
     depends_on:
       - postgres
     restart: always
     command: sh -c "/wait && ./rest-api"
     environment:
       - WAIT_HOSTS=postgres:5432
       - WAIT_HOSTS_TIMEOUT=300
       - WAIT_SLEEP_INTERVAL=30
       - WAIT_HOST_CONNECT_TIMEOUT=30
     networks:
       - app

  postgres:
    container_name: postgres_container
    hostname: postgres
    restart: always
    image: postgres:alpine

    environment:
      POSTGRES_DB: "links"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - app

  redis:
    image: "redis:alpine"
    container_name: redis_container
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - app

networks:
  app:
    driver: bridge