version: "3.9"
services:
  postgres:
    container_name: postgres_container
    hostname: postgres
    restart: always
    image: postgres:alpine

    environment:
      POSTGRES_DB: "links"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      TZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - app

  redis:
    image: "redis:alpine"
    container_name: redis_container
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - app

networks:
  app:
    driver: bridge